#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -f /usr/bin/apt ]]; then
    echo "\
        python3-dev \
        python3-pip" >> /mod-repo-packages-to-install.list
elif [[ -f /sbin/apk ]]; then
    echo "\
        python3-dev \
        py3-pip" >> /mod-repo-packages-to-install.list
fi
